feat: added secret env to common secret job

diff --git a/charts/nected/templates/server-once-job.yaml b/charts/nected/templates/server-once-job.yaml
--- a/charts/nected/templates/server-once-job.yaml
+++ b/charts/nected/templates/server-once-job.yaml
@@ -21,17 +21,59 @@ spec:
           - name: setup
             image: {{ .Values.autoSetup.image.repository }}:{{ .Values.autoSetup.image.tag }}
             imagePullPolicy: {{ .Values.autoSetup.image.pullPolicy }}
-            {{- with .Values.autoSetup.command }}
+            {{- if .Values.autoSetup.secretValue }}
+            env:
+              - name: SECRET_VALUE
+                value: {{ .Values.autoSetup.secretValue }}
+            {{- end }}
             command:
-              {{- toYaml . | nindent 14 }}
-            {{- end }}
-            {{- with .Values.autoSetup.args }}
-            args:
-              {{- toYaml . | nindent 14 }}
-            {{- end }}
-            {{- with .Values.autoSetup.resources }}
-            resources:
-              {{- toYaml . | nindent 14 }}
+            - /bin/sh
+            - -c
+            - |
+              # SECRET_VALUE is the env variable used to reuse-secret-key
+
+              SECRET_NAME="encryption-at-rest-secret"
+              KEY_NAME=encryption-at-rest
+              KEY_FILE="./$KEY_NAME"
+
+              echo "Checking if secret '$SECRET_NAME' exists..."
+
+              if kubectl get secret "$SECRET_NAME" &> /dev/null; then
+                  echo "Secret '$SECRET_NAME' already exists. Skipping creation."
+              elif [ -n "$SECRET_VALUE" ]; then
+                  echo "Secret '$SECRET_NAME' does not exist. Using passed SECRET_VALUE..."
+                  kubectl apply -f - <<EOF
+              apiVersion: v1
+              kind: Secret
+              metadata:
+                name: "$SECRET_NAME"
+              type: Opaque
+              data:
+                "$KEY_NAME": "$SECRET_VALUE"
+              EOF
+              else
+                  echo "Secret '$SECRET_NAME' does not exist. Creating..."
+
+                  echo "Generating RSA key..."
+                  openssl genrsa -f4 -out "$KEY_FILE" 4096
+
+                  if [ $? -eq 0 ]; then
+                      echo "Creating secret..."
+                      kubectl create secret generic "$SECRET_NAME" --from-file="$KEY_FILE"
+
+                      if [ $? -eq 0 ]; then
+                          echo "Key generated & secret created successfully."
+                          # Clean up the temporary key file for security
+                          rm -f "$KEY_FILE"
+                      else
+                          echo "Error: Failed to create secret."
+                          exit 1
+                      fi
+                  else
+                      echo "Error: Failed to generate RSA key."
+                      exit 1
+                  fi
+              fi
             {{- end }}
         restartPolicy: OnFailure
 {{- end }}
